import {spawn,spawnSync} from 'node:child_process';
import {createInterface} from 'node:readline';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {dirname,resolve} from 'node:path';
const output=process.argv[2];if(!output)throw Error('new result path required');
try{await readFile(output);throw Error('preserve prior evidence')}catch(e){if(e.code!=='ENOENT')throw e;}
const {chromium}=await import(pathToFileURL(`${process.env.HOME}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs`));
const operator=randomBytes(32).toString('base64url');
const instance=randomUUID();const ipcToken=randomBytes(32).toString('base64url');
const unity=process.argv.includes('--unity');
const observations=[];const childPids=new Set();let observedOverflow=false;const lifecycle=[];const started=performance.now();
const java=unity?spawn(resolve('Unity/Builds/FoundationLinux/GorillaEscape.x86_64'),['-screen-fullscreen','0','-screen-width','640','-screen-height','360','-logFile','-'],{env:{...process.env,GORILLA_IPC_JAVA:'/usr/lib/jvm/java-21-openjdk-amd64/bin/java',GORILLA_IPC_JAR:resolve('Server/target/local-server-0.1.0-SNAPSHOT.jar'),GORILLA_IPC_MODE:'lifecycle',GORILLA_PHONE_INPUT:'1',GORILLA_MOBILE_LAB:'1',GORILLA_MOBILE_OPERATOR:operator},stdio:['pipe','pipe','pipe']}):spawn('/usr/lib/jvm/java-21-openjdk-amd64/bin/java',['-Djava.net.preferIPv4Stack=true','-jar',resolve('Server/target/local-server-0.1.0-SNAPSHOT.jar'),'--gorilla.ipc.managed=true','--gorilla.mobile.rtc-enabled=true','--server.address=127.0.0.1','--server.port=0','--logging.config=classpath:ipc-logback.xml'],{env:{...process.env,GORILLA_IPC_INSTANCE:instance,GORILLA_IPC_TOKEN:ipcToken,GORILLA_MOBILE_LAB:'1',GORILLA_MOBILE_OPERATOR:operator,GORILLA_IPC_LOCK_DIR:`${process.env.HOME}/.gorilla-escape/managed`},stdio:['pipe','pipe','pipe']});
let stderrBytes=0;java.stderr.on('data',b=>stderrBytes+=b.length);
const exited=new Promise(r=>java.once('exit',(code,signal)=>r({code,signal})));
let readyResolve;const readiness=new Promise(r=>readyResolve=r);createInterface({input:java.stdout}).on('line',line=>{if(line.startsWith('{"component":"ipc-unity"')){try{const event=JSON.parse(line);if(lifecycle.length<200)lifecycle.push(event);if(event.event==='PROCESS_STARTED')childPids.add(event.pid);}catch{} }if(line.startsWith('PHONE_INPUT_OBSERVED ')){if(observations.length<10000)observations.push(JSON.parse(line.slice('PHONE_INPUT_OBSERVED '.length)));else observedOverflow=true;return;}if(line.startsWith('PHONE_LAB_HTTP_READY ')){readyResolve({httpPort:Number(line.slice('PHONE_LAB_HTTP_READY '.length))});return;}if(line.startsWith('GORILLA_IPC_READY '))readyResolve(JSON.parse(line.slice('GORILLA_IPC_READY '.length)));});
function deadline(p,ms){let t;return Promise.race([p,new Promise((_,j)=>t=setTimeout(()=>j(Error('deadline')),ms))]).finally(()=>clearTimeout(t));}
const result={scope:'Phase0 runtime Chrome/PWA adapter ↔ RTC ↔ Java; Unity NOT RUN in this harness',physical:'DEFERRED',runs:[],negatives:[],gate:'FAIL',cleanup:{}};
let browser;
try{
 const ready=await deadline(readiness,20000);result.startupMs=performance.now()-started;const base=`http://127.0.0.1:${ready.httpPort}`;browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});result.browser=browser.version();
 async function issue(){const response=await browser.newContext();try{const r=await response.request.post(base+'/mobile/admission',{headers:{'X-Gorilla-Operator':operator}});if(!r.ok())throw Error('admission rejected');const body=await r.json();if(!body.qrPng||!body.url)throw Error('QR missing');const decoded=spawnSync('/usr/lib/jvm/java-21-openjdk-amd64/bin/java',['--class-path',`${process.env.HOME}/.m2/repository/com/google/zxing/core/3.5.3/core-3.5.3.jar`,'tools/spikes/webrtc/DecodeQr.java'],{input:Buffer.from(body.qrPng,'base64'),maxBuffer:4096,timeout:10000});if(decoded.status!==0||decoded.stdout.toString()!==body.url)throw Error('QR decode mismatch');body.url=decoded.stdout.toString();result.qr='PNG → ZXing decoder → real admission PASS';return body;}finally{await response.close();}}
 async function client(admission,resume=null){const context=await browser.newContext();const page=await context.newPage();await page.goto(base+'/mobile-lab/index.html');await page.waitForFunction(()=>typeof MobileClient==='function');const identity=await page.evaluate(async({url,resume})=>{window.client=new MobileClient({source:'synthetic'});return await client.connect(url,resume)},{url:admission.url,resume});return {context,page,identity};}
 const admissions=[];for(let i=0;i<4;i++)admissions.push(await issue());const clients=[];for(const a of admissions)clients.push(await client(a));
 if(new Set(clients.map(c=>c.identity.playerId)).size!==4)throw Error('PlayerIds not unique');
 result.playerIds=clients.map(c=>c.identity.playerId);result.rtc=await Promise.all(clients.map(c=>c.page.evaluate(async()=>{const stats=await client.pc.getStats();const pairs=[...stats.values()].filter(x=>x.type==='candidate-pair'&&x.state==='succeeded'&&x.nominated).map(p=>({localType:stats.get(p.localCandidateId)?.candidateType,remoteType:stats.get(p.remoteCandidateId)?.candidateType,transport:stats.get(p.localCandidateId)?.protocol}));return {pairs,channels:Object.fromEntries(Object.entries(client.channels).map(([name,ch])=>[name,{ordered:ch.ordered,maxRetransmits:ch.maxRetransmits}])),stunTurnConfigured:client.pc.getConfiguration().iceServers.length};})));
 async function run(c,hz,n){return c.page.evaluate(async({hz,n,player})=>{
  const before={sent:client.metrics.sent,received:client.metrics.received,rtt:client.metrics.rtt.length};const started=performance.now();for(let i=0;i<n;i++){const payload=normalizeMotion({acceleration:{x:player,y:i,z:0},rotationRate:{alpha:i,beta:0,gamma:0}});await client.send('MOTION_SAMPLE',payload);const due=started+(i+1)*1000/hz;await new Promise(r=>setTimeout(r,Math.max(0,due-performance.now())));}
  const values=client.metrics.rtt.slice(before.rtt).sort((a,b)=>a-b);return {targetSyntheticHz:hz,n,source:'synthetic',sent:client.metrics.sent-before.sent,received:client.metrics.received-before.received,errors:client.metrics.errors,p50Ms:values[Math.ceil(values.length*.5)-1],p95Ms:values[Math.ceil(values.length*.95)-1],maximumMs:values.at(-1),durationMs:performance.now()-started};
 },{hz,n,player:c.identity.playerId});}
 for(const hz of [30,50,60])result.runs.push({hz,clients:await Promise.all(clients.map(c=>run(c,hz,60)))});
 const fixture=JSON.parse(await readFile('Shared/Protocol/mobile/motion-v1.json','utf8'));await clients[0].page.evaluate(async payload=>{client.source='replay';await client.send('MOTION_SAMPLE',payload);client.source='synthetic';},fixture.payload);result.replay={gate:'PASS',source:'replay',fixture:'Shared/Protocol/mobile/motion-v1.json'};
 const burst=await clients[3].page.evaluate(async()=>{const before=client.metrics.overwritten;for(let i=0;i<500;i++)client.motion(normalizeMotion({acceleration:{x:client.identity.playerId,y:i,z:0}}));await client.send('HEARTBEAT',{});const deadline=performance.now()+3000;while(client.inFlight&&performance.now()<deadline)await new Promise(r=>setTimeout(r,10));return {generated:500,overwritten:client.metrics.overwritten-before,pending:client.pending.size,latestPending:client.latest!==null,source:'synthetic'};});if(burst.pending!==0||burst.latestPending||burst.overwritten<490)throw Error('burst bounds');result.burst=burst;
 const captureResult=await clients[0].page.evaluate(async()=>{
  const capture=new SensorCapture();if(!await capture.start())throw Error('capture API unavailable in desktop lab');
  const detach=attachCapture(capture,client);
  for(let i=0;i<10;i++){const event=new Event('devicemotion');Object.assign(event,{acceleration:{x:client.identity.playerId,y:i,z:0},accelerationIncludingGravity:{x:0,y:9.81,z:0},rotationRate:{alpha:i,beta:0,gamma:0},interval:20});window.dispatchEvent(event);await new Promise(r=>setTimeout(r,25));}
  capture.suspend(true);if(capture.state!=='SUSPENDED')throw Error('suspend');await client.send('CLIENT_STATE',{state:'suspended'});capture.suspend(false);await client.send('CLIENT_STATE',{state:'active'});const events=capture.snapshot().channels.motion.events;detach();capture.stop();return {events,source:'synthetic DOM events through unchanged SensorCapture',lifecycle:'PASS'};
 });result.capture=captureResult;await clients[0].page.evaluate(()=>client.send('TOUCH',{touch:{availability:'present',values:{x:0.5,y:0.5,pressed:true}}}));result.touch='reliable TOUCH accepted PASS';
 result.negatives.push({case:'operator-unauthorized',gate:(await fetch(base+'/mobile/admission',{method:'POST'})).status===403?'PASS':'FAIL'});
 const forged=await clients[0].page.evaluate(async()=>{const message=client.envelope('MOTION_SAMPLE',normalizeMotion({acceleration:{x:1,y:2,z:3}}));message.playerId=2;return new Promise(r=>{const ch=client.channels.motion;const prior=ch.onmessage;const timer=setTimeout(()=>{ch.onmessage=prior;r('TIMEOUT')},2000);ch.onmessage=e=>{const n=JSON.parse(e.data);if(n.messageType==='ERROR'){clearTimeout(timer);ch.onmessage=prior;r('REJECTED')}else prior(e)};ch.send(JSON.stringify(message));});});result.negatives.push({case:'wrong-player',gate:forged==='REJECTED'?'PASS':'FAIL'});
 const corpus=await clients[0].page.evaluate(async()=>{const results=[];const invalid=[['unknown-version',m=>m.protocolVersion=2],['unknown-type',m=>m.messageType='SMASH'],['wrong-session',m=>m.sessionId='wrong'],['missing-field',m=>delete m.quality],['stale',m=>m.clientTimestamp-=3000],['future',m=>m.clientTimestamp+=10000],['malformed',()=>'{'],['oversized',()=> 'x'.repeat(2049)]];for(const [name,change] of invalid){const m=client.envelope('MOTION_SAMPLE',normalizeMotion({acceleration:{x:1,y:2,z:3}}));const raw=change(m);const outcome=await new Promise(resolve=>{const ch=client.channels.motion,prior=ch.onmessage;const t=setTimeout(()=>{ch.onmessage=prior;resolve('TIMEOUT')},2000);ch.onmessage=e=>{if(JSON.parse(e.data).messageType==='ERROR'){clearTimeout(t);ch.onmessage=prior;resolve('REJECTED')}else prior(e)};ch.send(typeof raw==='string'?raw:JSON.stringify(m));});results.push({case:name,gate:outcome==='REJECTED'?'PASS':'FAIL'});}return results;});result.negatives.push(...corpus);
 const rate=await clients[2].page.evaluate(async()=>{const ch=client.channels.motion,prior=ch.onmessage;let rejected=0,acknowledged=0;ch.onmessage=e=>{const n=JSON.parse(e.data);if(n.messageType==='ERROR')rejected++;else if(n.messageType==='ACK')acknowledged++;else prior(e);};const started=performance.now();for(let i=0;i<400;i++){while(ch.bufferedAmount>4096)await new Promise(r=>setTimeout(r,1));ch.send(JSON.stringify(client.envelope('MOTION_SAMPLE',normalizeMotion({acceleration:{x:client.identity.playerId,y:i,z:0}}))));}const sendDurationMs=performance.now()-started;await new Promise(r=>setTimeout(r,1100));ch.onmessage=prior;await client.send('HEARTBEAT',{});return {sent:400,acknowledged,rejected,sendDurationMs,gate:rejected>0?'PASS':'FAIL'};});result.pressure=rate;result.negatives.push({case:'rate-abuse-isolated-and-recovered',gate:rate.gate});await clients[1].page.evaluate(()=>client.send('HEARTBEAT',{}));
 const fullResponse=await clients[1].page.evaluate(async()=>{const body={protocolVersion:1,messageType:'JOIN',sessionId:client.identity.sessionId,admission:'invalid',offer:client.pc.localDescription.sdp};return (await fetch('/mobile/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})).status;});result.negatives.push({case:'fifth-peer-rejected-at-capacity',gate:fullResponse===400?'PASS':'FAIL'});
 const duplicate=await clients[1].page.evaluate(async()=>{try{await client.signal('/mobile/reconnect',{sessionId:client.identity.sessionId,playerId:client.identity.playerId,resumeToken:client.identity.resumeToken,offer:client.pc.localDescription.sdp});return 'FAIL';}catch{return 'PASS';}});result.negatives.push({case:'duplicate-active-client',gate:duplicate});
 const resumed=await clients[0].page.evaluate(()=>({...client.identity}));await clients[0].page.evaluate(()=>client.close());await clients[0].context.close();
 const joinNegatives=await clients[1].page.evaluate(async url=>{const fragment=new URLSearchParams(new URL(url).hash.slice(1)),cases=[['credential-replay',fragment.get('admission'),fragment.get('sessionId')],['invalid-credential','invalid',fragment.get('sessionId')],['wrong-session','invalid','wrong']];const results=[];for(const [name,admission,sessionId] of cases){try{await client.signal('/mobile/join',{protocolVersion:1,messageType:'JOIN',admission,sessionId,offer:client.pc.localDescription.sdp});results.push({case:name,gate:'FAIL'});}catch{results.push({case:name,gate:'PASS'});}}return results;},admissions[0].url);result.negatives.push(...joinNegatives);
 await clients[1].page.evaluate(()=>client.send('HEARTBEAT',{}));result.negatives.push({case:'one-disconnect-others-live',gate:'PASS'});
 const reconnected=await client({url:admissions[0].url},resumed);if(reconnected.identity.playerId!==resumed.playerId||reconnected.identity.connectionEpoch!==resumed.connectionEpoch+1)throw Error('reconnect identity');result.reconnect='PASS';await run(reconnected,30,10);await reconnected.page.evaluate(()=>client.close());await reconnected.context.close();
 for(const c of clients.slice(1)){await c.page.evaluate(()=>client.close());await c.context.close();}
 const diagnostics=await browser.newContext();const response=await diagnostics.request.get(base+'/mobile/diagnostics',{headers:{'X-Gorilla-Operator':operator}});result.javaDiagnostics=await response.json();if(result.javaDiagnostics.peers!==0)throw Error('residual peers');const end=await diagnostics.request.post(base+'/mobile/end',{headers:{'X-Gorilla-Operator':operator}});if(!end.ok())throw Error('session end');const closed=await diagnostics.request.post(base+'/mobile/admission',{headers:{'X-Gorilla-Operator':operator}});result.negatives.push({case:'session-closed',gate:closed.status()>=400?'PASS':'FAIL'});await diagnostics.close();
 result.gate=result.negatives.every(n=>n.gate==='PASS')&&result.runs.every(r=>r.clients.every(c=>c.errors===0&&c.sent===c.received))?'PASS':'FAIL';
}catch(e){result.error=e.message;}
finally{
 if(browser)await browser.close();if(unity){spawnSync('python3',['-c',`import sys;sys.path.insert(0,'tools');from validate_ipc_2b_player import X11;X11().close(${java.pid})`]);}else java.stdin.end();try{result.cleanup.java=await deadline(exited,10000)}catch{java.kill('SIGKILL');result.cleanup.java=await exited;result.cleanup.forced=true;result.gate='FAIL';}result.cleanup.stderrBytes=stderrBytes;if(unity){const stopped=lifecycle.findLast(e=>e.event==='STOPPED');result.cleanup.lifecycleStopped=stopped?{state:'STOPPED',exitCode:stopped.exitCode,cleanupComplete:stopped.cleanupComplete,forced:stopped.forced}:null;if(!stopped||!stopped.cleanupComplete||stopped.exitCode!==0)result.gate='FAIL';}result.cleanup.residualOwnedChildren=[...childPids].filter(pid=>{try{process.kill(pid,0);return true;}catch{return false;}}).length;if(result.cleanup.residualOwnedChildren||observedOverflow)result.gate='FAIL';if(unity){result.scope='Real Chrome/PWA → RTC → Java child owned by Unity → same loopback IPC → Unity Player PhoneInput';result.unityObservations=observations;result.unityGate=observations.length>0&&new Set(observations.map(x=>x.playerId)).size===4&&observations.every(x=>!x.accelerationXPresent||x.accelerationX===x.playerId)?'PASS':'FAIL';if(result.unityGate!=='PASS')result.gate='FAIL';}
 await mkdir(dirname(resolve(output)),{recursive:true});await writeFile(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({gate:result.gate,error:result.error,ids:result.playerIds,cleanup:result.cleanup}));
}
process.exitCode=result.gate==='PASS'?0:1;
