import test from 'node:test';import assert from 'node:assert/strict';
import {MobileClient,sanitizeCandidate} from '../src/input/mobileClient.js';
class Channel extends EventTarget {constructor(label,pc){super();this.label=label;this.pc=pc;this.readyState='connecting';this.bufferedAmount=0;}open(){this.readyState='open';this.dispatchEvent(new Event('open'));this.onopen?.();}send(text){const n=JSON.parse(text);queueMicrotask(()=>this.onmessage?.({data:JSON.stringify({...n,messageType:'ACK'})}));}close(){this.readyState='closed';this.dispatchEvent(new Event('close'));this.onclose?.();}}
class Peer extends EventTarget {
 constructor(){super();this.signalingState='stable';this.iceGatheringState='new';this.iceConnectionState='new';this.connectionState='new';this.channels=[];}
 createDataChannel(label){const c=new Channel(label,this);this.channels.push(c);return c;}
 async createOffer(){return {type:'offer',sdp:'v=0 SECRET-SDP'};}
 async setLocalDescription(d){this.localDescription=d;this.signalingState='have-local-offer';this.iceGatheringState='complete';const e=new Event('icecandidate');e.candidate={candidate:'candidate:1 1 udp 1 private-name.local 52741 typ host'};this.dispatchEvent(e);this.dispatchEvent(new Event('icegatheringstatechange'));}
 async setRemoteDescription(){this.iceConnectionState='connected';this.connectionState='connected';this.dispatchEvent(new Event('iceconnectionstatechange'));this.channels.forEach(c=>c.open());}
 close(){this.iceConnectionState='closed';this.connectionState='closed';this.dispatchEvent(new Event('iceconnectionstatechange'));}
}
const setup=()=>{globalThis.RTCPeerConnection=Peer;globalThis.location={href:'https://example.test/mobile-lab/index.html'};};
const url='https://example.test/#sessionId=SECRET-SESSION&admission=SECRET-ADMISSION';
test('candidate metadata never retains addresses or SDP',()=>{for(const [address,kind] of [['192.168.1.5','IPV4'],['fd00::5','IPV6'],['private-name.local','MDNS_LOCAL']]){const d=sanitizeCandidate(`candidate:1 1 UDP 1 ${address} 52741 typ host`);assert.equal(d.addressKind,kind);assert.equal(d.port,52741);assert.ok(!JSON.stringify(d).includes(address));}assert.equal(sanitizeCandidate('candidate:secret invalid'),null);});
test('successful connect stages and bounded report exclude credentials',async()=>{setup();const c=new MobileClient({fetcher:async()=>({ok:true,status:200,json:async()=>({sessionId:'SECRET-SESSION',resumeToken:'SECRET-RESUME',answer:'SECRET-SDP'})})});await c.connect(url);assert.equal(c.trace.stage,'READY');for(const stage of ['CREATE_OFFER','LOCAL_DESCRIPTION','ICE_GATHERING','SIGNALING_POST','SIGNALING_RESPONSE','REMOTE_DESCRIPTION','CONTROL_OPEN','MOTION_OPEN','HELLO_ACK','READY'])assert.ok(c.trace.events.some(e=>e.value===stage));assert.equal(c.trace.remoteDescription,'PASS');for(let i=0;i<200;i++)c.stage('READY');assert.equal(c.trace.events.length,96);assert.ok(!JSON.stringify(c.diagnostic()).includes('SECRET'));assert.ok(!JSON.stringify(c.diagnostic()).includes('private-name'));await c.close(false);});
test('HTTP rejection is distinguished; native/untrusted text never escapes',async()=>{setup();const c=new MobileClient({fetcher:async()=>({ok:false,status:400,json:async()=>({error:'SECRET-SDP',code:'ADMISSION_EXPIRED_OR_USED'})})});await assert.rejects(c.connect(url),/JOIN_E04_SIGNAL_REJECTED/);assert.equal(c.trace.postExecuted,true);assert.equal(c.trace.httpStatus,400);assert.equal(c.trace.rejectionCode,'ADMISSION_EXPIRED_OR_USED');assert.equal(c.trace.stage,'SIGNALING_RESPONSE');assert.ok(!JSON.stringify(c.diagnostic()).includes('SECRET'));});
test('network exception maps to HTTP stage without reflecting its message',async()=>{setup();const c=new MobileClient({fetcher:async()=>{throw Error('SECRET-URL');}});await assert.rejects(c.connect(url),/^Error: JOIN_E03_SIGNAL_HTTP$/);assert.equal(c.trace.httpStatus,null);assert.equal(c.trace.stage,'SIGNALING_POST');assert.ok(!JSON.stringify(c.diagnostic()).includes('SECRET'));});
test('unknown server error is sanitized',async()=>{setup();const c=new MobileClient({fetcher:async()=>({ok:false,status:400,json:async()=>({code:'SECRET-NATIVE-ERROR'})})});await assert.rejects(c.connect(url),/JOIN_E04_SIGNAL_REJECTED/);assert.equal(c.trace.rejectionCode,'SIGNAL_FAILED_OTHER');});
