using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using GorillaEscape.Contracts;
using GorillaEscape.Input;
using NUnit.Framework;

namespace GorillaEscape.Tests
{
    public sealed class OfficialActionLedgerTests
    {
        private long clock;
        private PhoneInputStore store;
        [SetUp] public void Setup() {clock=1000;store=new PhoneInputStore(()=>clock);}
        private void Input(int player=1,long sequence=1,long epoch=1,string state="ACTIVE",string type="TOUCH")
        {Assert.IsTrue(store.Accept(new PhoneInputWire{sessionId="session",deviceSessionId="device"+player,playerId=player,sequence=sequence,connectionEpoch=epoch,connectionState=state,messageType=type,serverReceiveTimestamp=clock,quality=new PhoneQuality{source="synthetic",status="valid"}}));}
        private ActionKey Key(int player=1,string kind="test") {Assert.IsTrue(store.TryActionSource(player,kind,out var key));return key;}
        private ActionKey Begin(int player=1,long sequence=1,long epoch=1) {Input(player,sequence,epoch);var key=Key(player);Assert.AreEqual(ActionDecision.CREATED,store.Actions.TryBegin(key,out _));return key;}
        private void Disconnect(int player=1,long epoch=1) {Input(player,1,epoch,"DISCONNECTED","SERVER_STATE");}
        private OfficialActionRecord Get(ActionKey key) {Assert.IsTrue(store.Actions.TryGet(key,out var record));return record;}
        [Test] public void CandidateRequiresExplicitUnityAuthority() {Input();Assert.AreEqual(0,store.Actions.Count);var key=Key();Assert.AreEqual(ActionDecision.CREATED,store.Actions.TryBegin(key,out var record));Assert.AreEqual(OfficialActionState.CANDIDATE,record.State);Assert.IsNull(record.Result);}
        [Test] public void DuplicateCandidateAndSemanticAliasRejected() {var key=Begin();Assert.AreEqual(ActionDecision.DUPLICATE,store.Actions.TryBegin(key,out _));Assert.AreEqual(ActionDecision.DUPLICATE,store.Actions.TryBegin(Key(1,"alias"),out _));Assert.AreEqual(1,store.Actions.Count);}
        [Test] public void DisconnectCancelsCandidateAndCannotResurrect() {var key=Begin();Disconnect();Assert.AreEqual(OfficialActionState.CANCELLED,Get(key).State);Assert.AreEqual(ActionDecision.TERMINAL,store.Actions.Confirm(key,"ok",out _));Assert.AreEqual(ActionDecision.DUPLICATE,store.Actions.TryBegin(key,out _));Assert.IsNull(Get(key).Result);}
        [Test] public void ConfirmedResultSurvivesDisconnectAndReconnect() {var key=Begin();Assert.AreEqual(ActionDecision.CONFIRMED,store.Actions.Confirm(key,"ok",out var record));var result=record.Result;Disconnect();Input(epoch:2);Assert.AreSame(result,Get(key).Result);Assert.AreEqual(OfficialActionState.CONFIRMED,Get(key).State);Assert.AreEqual(ActionDecision.TERMINAL,store.Actions.Cancel(key));}
        [Test] public void DuplicateConfirmIsIdempotentAndConflictRejected() {var key=Begin();Assert.AreEqual(ActionDecision.CONFIRMED,store.Actions.Confirm(key,"ok",out var first));clock++;Assert.AreEqual(ActionDecision.IDEMPOTENT,store.Actions.Confirm(key,"ok",out var second));Assert.AreSame(first.Result,second.Result);Assert.AreEqual(ActionDecision.CONFLICT,store.Actions.Confirm(key,"different",out _));Assert.AreEqual("ok",Get(key).Result.OutcomeCode);}
        [Test] public void OldEpochRejectedNewEpochSameSequenceIndependent() {var key=Begin();Input(epoch:2);Assert.AreEqual(OfficialActionState.CANCELLED,Get(key).State);Assert.AreEqual(ActionDecision.DUPLICATE,store.Actions.TryBegin(key,out _));var fabricated=new ActionKey("session","device1",1,1,2,"late");Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(fabricated,out _));Assert.AreEqual(ActionDecision.CREATED,store.Actions.TryBegin(Key(),out _));Assert.AreNotEqual(key,Key());}
        [Test] public void OldInputCannotReplaceCurrentEpoch() {Input(epoch:2);var old=new PhoneInputWire{playerId=1,sequence=9,connectionEpoch=1,sessionId="session",deviceSessionId="device1",quality=new PhoneQuality(),serverReceiveTimestamp=clock};Assert.IsFalse(store.Accept(old));Assert.AreEqual(2,Key().ConnectionEpoch);}
        [Test] public void LateSequenceAndUnknownIdentityRejected() {Begin(sequence:5);Input(sequence:6);var old=new ActionKey("session","device1",1,1,4,"old");Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(old,out _));Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(new ActionKey("other","device1",1,1,6,"test"),out _));Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(new ActionKey("session","other",1,1,6,"test"),out _));}
        [Test] public void FourPlayersAreIsolated() {var keys=Enumerable.Range(1,4).Select(p=>Begin(p)).ToArray();Disconnect(2);for(int i=0;i<4;i++)Assert.AreEqual(i==1?OfficialActionState.CANCELLED:OfficialActionState.CANDIDATE,Get(keys[i]).State);Assert.AreEqual(4,store.Actions.Count);}
        [Test] public void ExplicitCancellationIsTerminal() {var key=Begin();Assert.AreEqual(ActionDecision.CANCELLED,store.Actions.Cancel(key));Assert.AreEqual(ActionDecision.TERMINAL,store.Actions.Cancel(key));Assert.AreEqual(ActionDecision.TERMINAL,store.Actions.Confirm(key,"ok",out _));}
        [TestCase("SUSPENDED")][TestCase("CONNECTED")][TestCase("DISCONNECTED")]
        public void ServerInvalidationCancels(string state) {var key=Begin();Input(state:state,type:"SERVER_STATE");Assert.AreEqual(OfficialActionState.CANCELLED,Get(key).State);}
        [Test] public void StaleInputCannotConfirm() {var key=Begin();clock+=OfficialActionLedger.FreshnessMilliseconds;Assert.AreEqual(ActionDecision.TERMINAL,store.Actions.Confirm(key,"ok",out _));Assert.AreEqual(OfficialActionState.CANCELLED,Get(key).State);}
        [Test] public void LobbyInvalidationCancelsWithoutAnotherInput() {var key=Begin();store.ObserveLobby(new LobbySnapshotWire{sessionId="session",players=new[]{new LobbyPlayerWire{playerId=1,deviceSessionId="device1",connectionEpoch=1,connectionState="ACTIVE",networkReady=true,inputReady=false}}});Assert.AreEqual(OfficialActionState.CANCELLED,Get(key).State);Input(sequence:2);Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(Key(),out _));}
        [Test] public void SessionEndPreservesConfirmedAndResetCleans() {var confirmed=Begin();store.Actions.Confirm(confirmed,"ok",out _);var candidate=Begin(sequence:2);store.EndSession();Assert.AreEqual(OfficialActionState.CANCELLED,Get(candidate).State);Assert.AreEqual("ok",Get(confirmed).Result.OutcomeCode);store.Clear();Assert.AreEqual(0,store.Actions.Count);Assert.IsFalse(store.TryLatest(1,out _));Assert.AreEqual(ActionDecision.UNKNOWN,store.Actions.Confirm(confirmed,"ok",out _));Assert.AreEqual(ActionDecision.STALE,store.Actions.TryBegin(confirmed,out _));}
        [Test] public void CapacityRetainsEveryResultAndHighWaterRejectsReplay() {ActionKey first=default;for(int i=1;i<=OfficialActionLedger.MaximumActions;i++){var key=Begin(sequence:i);if(i==1)first=key;store.Actions.Confirm(key,"ok",out _);}Input(sequence:257);Assert.AreEqual(ActionDecision.CAPACITY,store.Actions.TryBegin(Key(),out _));Assert.AreEqual(256,store.Actions.Count);Disconnect();Input(epoch:2);Assert.AreEqual(ActionDecision.CAPACITY,store.Actions.TryBegin(Key(),out _));Assert.AreEqual("ok",Get(first).Result.OutcomeCode);Assert.AreEqual(ActionDecision.DUPLICATE,store.Actions.TryBegin(first,out _));}
        [Test] public void InvalidKeysAndResultsRejected() {Input();Assert.AreEqual(ActionDecision.INVALID,store.Actions.TryBegin(Key(1,"bad secret text"),out _));var key=Key();store.Actions.TryBegin(key,out _);Assert.AreEqual(ActionDecision.INVALID,store.Actions.Confirm(key,new string('x',65),out _));Assert.AreEqual(OfficialActionState.CANDIDATE,Get(key).State);}
        [Test] public void ConfirmWinsThenDisconnectPreservesResult() {var key=Begin();store.Actions.Confirm(key,"ok",out _);Disconnect();Assert.AreEqual(OfficialActionState.CONFIRMED,Get(key).State);}
        [Test] public void RaceConfirmDisconnectHasExactlyOneTerminalState() {for(int i=0;i<100;i++){store.Clear();var key=Begin();using(var start=new Barrier(2)){var a=Task.Run(()=>{start.SignalAndWait();return store.Actions.Confirm(key,"ok",out _);});var b=Task.Run(()=>{start.SignalAndWait();Disconnect();});Task.WaitAll(a,b);var record=Get(key);Assert.IsTrue(record.State==OfficialActionState.CONFIRMED||record.State==OfficialActionState.CANCELLED);Assert.AreEqual(record.State==OfficialActionState.CONFIRMED,record.Result!=null);Assert.AreEqual(record.State==OfficialActionState.CONFIRMED?ActionDecision.CONFIRMED:ActionDecision.TERMINAL,a.Result);}}}
        [Test] public void ConcurrentConfirmsProduceOneNewResult() {for(int i=0;i<100;i++){store.Clear();var key=Begin();using(var start=new Barrier(8)){var tasks=Enumerable.Range(0,8).Select(_=>Task.Run(()=>{start.SignalAndWait();return store.Actions.Confirm(key,"ok",out var record);})).ToArray();Task.WaitAll(tasks);Assert.AreEqual(1,tasks.Count(t=>t.Result==ActionDecision.CONFIRMED));Assert.AreEqual(7,tasks.Count(t=>t.Result==ActionDecision.IDEMPOTENT));Assert.AreEqual(OfficialActionState.CONFIRMED,Get(key).State);}}}
    }
}
